version: "3.5"

networks:
  mynet:
    name: mynet
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynet
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:  ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - mynet
    volumes:
      - wp:/var/www/wordpress
    restart:  on-failure

  nginx:
    container_name: nginx
    build:  ./requirements/nginx
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - mynet 
    restart: on-failure

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/bditte/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/bditte/data/mariadb

