version: "3.8"
services:
: '   db:
      build: 
         ./requirements/mariadb/
      ports:
         - "3306:3306"
      networks:
         - mynet
      #volumes
'
  nginx:
      build: 
          ./requirements/nginx
      container-name:
          "nginx"
      ports: 
        - "443:443"
      environment:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERTS_DIR=${CERTS_DIR}
        - TLS_VERSION=${TLS_VERSION}
        - PHP_FPM_HOST=${PHP_FPM_HOST}
        - PHP_FPM_PORT=${PHP_FPM_PORT}
        - VIRTUAL_PORT=443
        - VIRTUAL_HOST=${DOMAIN_NAME}
      
      restart:
          always

: '     networks:
        - mynet '

   wordpress:
      build: 
        ./requirements/wordpress
      container-name:
        "wordpress"
      depends-on:
        - maria-db
      networks:
        - mynet
      volumes:
        - "~/inception/volumes/wordpress:/var/www/html"
      restart:
        always
: '
networks:
   default:
      name: mynet
      external: true
'